import { jsPDF } from "jspdf";
import type { ScanData, Recommendation } from "../types/scan";

// ─── Color Palette ───────────────────────────────────────────────────────────
const COLORS = {
  primary: [37, 99, 235] as [number, number, number],      // blue-600
  primaryDark: [30, 64, 175] as [number, number, number],   // blue-800
  accent: [99, 102, 241] as [number, number, number],       // indigo-500
  danger: [220, 38, 38] as [number, number, number],        // red-600
  warning: [217, 119, 6] as [number, number, number],       // amber-600
  success: [22, 163, 74] as [number, number, number],       // green-600
  text: [15, 23, 42] as [number, number, number],           // slate-900
  textMuted: [100, 116, 139] as [number, number, number],   // slate-500
  textLight: [148, 163, 184] as [number, number, number],   // slate-400
  bg: [248, 250, 252] as [number, number, number],          // slate-50
  bgCard: [241, 245, 249] as [number, number, number],      // slate-100
  border: [226, 232, 240] as [number, number, number],      // slate-200
  white: [255, 255, 255] as [number, number, number],
};

// ─── Helpers ─────────────────────────────────────────────────────────────────
const PAGE_W = 210; // A4 width in mm
const PAGE_H = 297; // A4 height in mm
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;
const FOOTER_Y = PAGE_H - 14;

function setColor(pdf: jsPDF, c: [number, number, number]) {
  pdf.setTextColor(c[0], c[1], c[2]);
}

function setFillColor(pdf: jsPDF, c: [number, number, number]) {
  pdf.setFillColor(c[0], c[1], c[2]);
}

function setDrawColor(pdf: jsPDF, c: [number, number, number]) {
  pdf.setDrawColor(c[0], c[1], c[2]);
}

function addFooter(pdf: jsPDF, pageNum: number, totalPages: number) {
  setColor(pdf, COLORS.textLight);
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "normal");
  pdf.text("Generated by Digital Footprint Analyzer", MARGIN, FOOTER_Y);
  pdf.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN, FOOTER_Y, { align: "right" });
  // Thin line above footer
  setDrawColor(pdf, COLORS.border);
  pdf.setLineWidth(0.3);
  pdf.line(MARGIN, FOOTER_Y - 4, PAGE_W - MARGIN, FOOTER_Y - 4);
}

function ensureSpace(pdf: jsPDF, y: number, needed: number): number {
  if (y + needed > FOOTER_Y - 10) {
    pdf.addPage();
    return MARGIN + 5;
  }
  return y;
}

function drawSectionTitle(pdf: jsPDF, title: string, y: number, icon?: string): number {
  y = ensureSpace(pdf, y, 14);
  // Accent bar
  setFillColor(pdf, COLORS.primary);
  pdf.roundedRect(MARGIN, y, 3, 10, 1.5, 1.5, "F");
  // Title text
  setColor(pdf, COLORS.text);
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text(`${icon ? icon + "  " : ""}${title}`, MARGIN + 7, y + 7);
  return y + 16;
}

function drawKeyValue(pdf: jsPDF, key: string, value: string, x: number, y: number, maxW: number): number {
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "normal");
  setColor(pdf, COLORS.textMuted);
  pdf.text(key, x, y);
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "bold");
  setColor(pdf, COLORS.text);
  const lines = pdf.splitTextToSize(value || "—", maxW);
  pdf.text(lines, x, y + 4.5);
  return y + 4.5 + lines.length * 4;
}

function truncate(str: string, max: number): string {
  if (!str) return "—";
  return str.length > max ? str.substring(0, max - 3) + "..." : str;
}

// ─── Table Helpers ───────────────────────────────────────────────────────────
interface TableColumn {
  header: string;
  width: number;
  key: string;
}

function drawTableHeader(pdf: jsPDF, cols: TableColumn[], y: number): number {
  y = ensureSpace(pdf, y, 10);
  setFillColor(pdf, COLORS.primaryDark);
  pdf.roundedRect(MARGIN, y, CONTENT_W, 8, 1, 1, "F");
  pdf.setFontSize(7.5);
  pdf.setFont("helvetica", "bold");
  setColor(pdf, COLORS.white);
  let x = MARGIN + 3;
  for (const col of cols) {
    pdf.text(col.header, x, y + 5.5);
    x += col.width;
  }
  return y + 10;
}

function drawTableRow(pdf: jsPDF, cols: TableColumn[], row: Record<string, string>, y: number, isAlt: boolean): number {
  y = ensureSpace(pdf, y, 9);
  if (isAlt) {
    setFillColor(pdf, COLORS.bgCard);
    pdf.roundedRect(MARGIN, y, CONTENT_W, 8, 0.5, 0.5, "F");
  }
  pdf.setFontSize(7.5);
  pdf.setFont("helvetica", "normal");
  setColor(pdf, COLORS.text);
  let x = MARGIN + 3;
  for (const col of cols) {
    const val = truncate(row[col.key] || "—", Math.floor(col.width / 1.7));
    pdf.text(val, x, y + 5.5);
    x += col.width;
  }
  return y + 8.5;
}

// ═════════════════════════════════════════════════════════════════════════════
// MAIN EXPORT FUNCTION
// ═════════════════════════════════════════════════════════════════════════════
export function generatePDFReport(
  scanData: ScanData,
  recommendations: Recommendation[],
  queryLabel: string
) {
  const pdf = new jsPDF("p", "mm", "a4");
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const timeStr = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const socialCount = scanData.socialResults?.length || 0;
  const breachCount = scanData.breachResults?.length || 0;
  const googleCount = scanData.googleResults?.length || 0;
  const mentionCount = scanData.mentionResults?.length || 0;
  const riskScore = scanData.riskScore?.score || 0;
  const riskLevel = scanData.riskScore?.level || "Low";

  // ── PAGE 1: COVER ──────────────────────────────────────────────────────────
  // Top gradient bar
  setFillColor(pdf, COLORS.primary);
  pdf.rect(0, 0, PAGE_W, 72, "F");
  setFillColor(pdf, COLORS.primaryDark);
  pdf.rect(0, 0, PAGE_W, 4, "F");

  // Brand
  setColor(pdf, COLORS.white);
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "bold");
  pdf.text("DIGITAL FOOTPRINT ANALYZER", MARGIN, 22);
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "normal");
  pdf.text("Comprehensive Security & Exposure Assessment", MARGIN, 29);

  // Title
  pdf.setFontSize(28);
  pdf.setFont("helvetica", "bold");
  pdf.text("Security Report", MARGIN, 50);

  // Date badge
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "normal");
  pdf.text(`${dateStr}  •  ${timeStr}`, MARGIN, 60);

  // Identity card
  let y = 88;
  setFillColor(pdf, COLORS.bg);
  pdf.roundedRect(MARGIN, y, CONTENT_W, 44, 4, 4, "F");
  setDrawColor(pdf, COLORS.border);
  pdf.setLineWidth(0.3);
  pdf.roundedRect(MARGIN, y, CONTENT_W, 44, 4, 4, "S");

  pdf.setFontSize(8);
  pdf.setFont("helvetica", "bold");
  setColor(pdf, COLORS.textMuted);
  pdf.text("SCANNED IDENTITY", MARGIN + 8, y + 9);

  y += 14;
  drawKeyValue(pdf, "Name", scanData.input?.name || "—", MARGIN + 8, y, CONTENT_W / 2 - 10);
  drawKeyValue(pdf, "Email", scanData.input?.email || "—", MARGIN + CONTENT_W / 2, y, CONTENT_W / 2 - 10);
  y += 12;
  drawKeyValue(pdf, "Username", scanData.input?.username || "—", MARGIN + 8, y, CONTENT_W / 2 - 10);
  drawKeyValue(pdf, "Report Query", queryLabel || "—", MARGIN + CONTENT_W / 2, y, CONTENT_W / 2 - 10);

  // Risk Score Badge
  y = 148;
  const riskColor = riskScore >= 70 ? COLORS.danger : riskScore >= 40 ? COLORS.warning : COLORS.success;
  setFillColor(pdf, riskColor);
  pdf.circle(MARGIN + 22, y + 22, 22, "F");
  setColor(pdf, COLORS.white);
  pdf.setFontSize(24);
  pdf.setFont("helvetica", "bold");
  pdf.text(String(riskScore), MARGIN + 22, y + 25, { align: "center" });
  pdf.setFontSize(7);
  pdf.text("RISK", MARGIN + 22, y + 32, { align: "center" });

  // Metrics next to risk
  const metricsX = MARGIN + 55;
  const metrics = [
    { label: "PROFILES DETECTED", value: String(socialCount), color: COLORS.primary },
    { label: "BREACH RECORDS", value: String(breachCount), color: COLORS.danger },
    { label: "SEARCH MENTIONS", value: String(googleCount), color: COLORS.accent },
    { label: "ACTIVITY MENTIONS", value: String(mentionCount), color: COLORS.warning },
  ];
  let my = y + 2;
  for (const m of metrics) {
    setColor(pdf, m.color);
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.text(m.value, metricsX, my + 4);
    setColor(pdf, COLORS.textMuted);
    pdf.setFontSize(7);
    pdf.setFont("helvetica", "normal");
    pdf.text(m.label, metricsX + 18, my + 4);
    my += 11;
  }

  // Risk level badge
  setFillColor(pdf, riskColor);
  pdf.roundedRect(metricsX + 80, y + 8, 36, 10, 3, 3, "F");
  setColor(pdf, COLORS.white);
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "bold");
  pdf.text(riskLevel.toUpperCase() + " RISK", metricsX + 98, y + 15, { align: "center" });

  // ── PAGE 2+: EXECUTIVE SUMMARY (AI) ────────────────────────────────────────
  pdf.addPage();
  y = MARGIN + 5;
  y = drawSectionTitle(pdf, "Executive Summary", y);

  if (scanData.aiSummary) {
    setFillColor(pdf, [239, 246, 255]); // blue-50
    const summaryLines = pdf.splitTextToSize(scanData.aiSummary, CONTENT_W - 16);
    const blockH = Math.min(summaryLines.length * 4.2 + 10, FOOTER_Y - y - 15);
    pdf.roundedRect(MARGIN, y, CONTENT_W, blockH, 3, 3, "F");
    setColor(pdf, COLORS.text);
    pdf.setFontSize(8.5);
    pdf.setFont("helvetica", "normal");
    let lineY = y + 7;
    for (const line of summaryLines) {
      lineY = ensureSpace(pdf, lineY, 5);
      pdf.text(line, MARGIN + 8, lineY);
      lineY += 4.2;
    }
    y = lineY + 6;
  } else {
    setColor(pdf, COLORS.textMuted);
    pdf.setFontSize(9);
    pdf.text("No AI summary available for this scan.", MARGIN, y + 5);
    y += 14;
  }

  // ── SOCIAL PROFILES TABLE ──────────────────────────────────────────────────
  y = drawSectionTitle(pdf, "Social Profiles Detected", y);

  if (socialCount > 0) {
    const socialCols: TableColumn[] = [
      { header: "#", width: 8, key: "num" },
      { header: "Platform", width: 30, key: "platform" },
      { header: "Username", width: 30, key: "username" },
      { header: "URL", width: 72, key: "url" },
      { header: "Source", width: 26, key: "source" },
      { header: "Status", width: 18, key: "status" },
    ];
    y = drawTableHeader(pdf, socialCols, y);
    scanData.socialResults.forEach((s, i) => {
      y = drawTableRow(pdf, socialCols, {
        num: String(i + 1),
        platform: s.platform || "Unknown",
        username: s.username || "—",
        url: s.url || "—",
        source: s.source === "search" ? "Search-inferred" : s.source === "direct" ? "Verified" : s.source || "—",
        status: s.found ? "Found" : "Not found",
      }, y, i % 2 === 1);
    });
    y += 6;
  } else {
    setColor(pdf, COLORS.textMuted);
    pdf.setFontSize(9);
    pdf.text("No social profiles were detected in this scan.", MARGIN, y + 5);
    y += 14;
  }

  // ── BREACH RECORDS TABLE ───────────────────────────────────────────────────
  y = drawSectionTitle(pdf, "Breach Records", y);

  if (breachCount > 0) {
    const breachCols: TableColumn[] = [
      { header: "#", width: 8, key: "num" },
      { header: "Platform / Source", width: 38, key: "platform" },
      { header: "Date", width: 26, key: "date" },
      { header: "Severity", width: 22, key: "severity" },
      { header: "Data Exposed", width: 80, key: "data" },
    ];
    y = drawTableHeader(pdf, breachCols, y);
    scanData.breachResults.forEach((b, i) => {
      y = drawTableRow(pdf, breachCols, {
        num: String(i + 1),
        platform: b.platform || b.name || b.domain || "Unknown",
        date: b.date || b.breachDate || "—",
        severity: (b.severity || "—").toUpperCase(),
        data: (b.dataExposed || b.dataClasses || []).join(", ") || "—",
      }, y, i % 2 === 1);
    });
    y += 6;
  } else {
    setColor(pdf, COLORS.textMuted);
    pdf.setFontSize(9);
    pdf.text("No breach records were found for this identity.", MARGIN, y + 5);
    y += 14;
  }

  // ── SEARCH VISIBILITY ─────────────────────────────────────────────────────
  y = drawSectionTitle(pdf, "Search Visibility (Google)", y);

  if (googleCount > 0) {
    scanData.googleResults.slice(0, 15).forEach((g, i) => {
      y = ensureSpace(pdf, y, 18);
      // Numbered item
      setColor(pdf, COLORS.primary);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.text(`${i + 1}.`, MARGIN, y + 4);
      // Title
      setColor(pdf, COLORS.text);
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "bold");
      const titleLines = pdf.splitTextToSize(g.title || "Untitled", CONTENT_W - 10);
      pdf.text(titleLines[0], MARGIN + 7, y + 4);
      // URL
      setColor(pdf, COLORS.primary);
      pdf.setFontSize(7);
      pdf.setFont("helvetica", "normal");
      pdf.text(truncate(g.link || "", 100), MARGIN + 7, y + 9);
      // Snippet
      if (g.snippet) {
        setColor(pdf, COLORS.textMuted);
        pdf.setFontSize(7.5);
        const snippetLines = pdf.splitTextToSize(g.snippet, CONTENT_W - 10);
        pdf.text(snippetLines.slice(0, 2), MARGIN + 7, y + 13.5);
      }
      y += 20;
    });
    if (googleCount > 15) {
      setColor(pdf, COLORS.textMuted);
      pdf.setFontSize(8);
      pdf.text(`... and ${googleCount - 15} more results`, MARGIN, y + 3);
      y += 8;
    }
  } else {
    setColor(pdf, COLORS.textMuted);
    pdf.setFontSize(9);
    pdf.text("No search results were found.", MARGIN, y + 5);
    y += 14;
  }

  // ── RECOMMENDATIONS ────────────────────────────────────────────────────────
  y = drawSectionTitle(pdf, "Security Recommendations", y);

  if (recommendations.length > 0) {
    recommendations.forEach((r, i) => {
      y = ensureSpace(pdf, y, 18);
      const prioColor = r.priority === "high" ? COLORS.danger : r.priority === "medium" ? COLORS.warning : COLORS.success;
      // Priority dot
      setFillColor(pdf, prioColor);
      pdf.circle(MARGIN + 3, y + 3, 2, "F");
      // Title
      setColor(pdf, COLORS.text);
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "bold");
      pdf.text(r.title, MARGIN + 8, y + 4.5);
      // Priority label
      setColor(pdf, prioColor);
      pdf.setFontSize(7);
      pdf.setFont("helvetica", "bold");
      pdf.text(r.priority.toUpperCase(), PAGE_W - MARGIN, y + 4.5, { align: "right" });
      // Description
      setColor(pdf, COLORS.textMuted);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "normal");
      const descLines = pdf.splitTextToSize(r.description, CONTENT_W - 12);
      pdf.text(descLines.slice(0, 2), MARGIN + 8, y + 10);
      y += 8 + descLines.slice(0, 2).length * 4;
    });
  }

  // ── ADD FOOTERS TO ALL PAGES ───────────────────────────────────────────────
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    addFooter(pdf, i, totalPages);
  }

  // ── SAVE ───────────────────────────────────────────────────────────────────
  const safeName = (queryLabel || "report").replace(/[^a-zA-Z0-9]/g, "_").substring(0, 30);
  const dateSlug = now.toISOString().split("T")[0];
  pdf.save(`DigitalFootprint_${safeName}_${dateSlug}.pdf`);
}
